Repository FrancoA56/FinalProjectClient, pull requests merged in 2023-10, with the labels that each got.

#71 feature/cart local storage
  src/App.js
  src/Redux/actions.js
  src/Redux/reducer.js
  src/Redux/types.js
  src/components/Cart/cart.jsx
  src/components/Nav/Nav.jsx
Labels: ready to review

#76 Feature/password
  package-lock.json
  package.json
  src/components/Nav/nav.module.css
  src/components/registerComponents/registerComponents.jsx
  src/components/validation.js
Labels: ready to review

#78 Feature/profile
  src/components/Profile/Profile.jsx
Labels: Ready to Merge

#80 Fix/profile
  src/App.js
  src/Redux/actions.js
  src/Redux/reducer.js
  src/Redux/types.js
  src/components/Nav/Nav.jsx
  src/components/Profile/Profile.jsx
  src/views/profile/profileView.js
Labels: Ready to Merge

#82 Add components Forgot password
  src/App.js
  src/components/ForgotPassword/ForgotPassword.jsx
  src/components/ResetPassword/ResetPassword.jsx
  src/components/loginComponents/loginComponents.jsx
  src/utils/img/loading.png
Labels: ready to review

#83 Feature/deploy
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Redux/actions.js
  src/components/Detail/Detail.jsx
  src/components/Profile/Profile.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
  src/components/shoppingCart/Plantillas.jsx
Labels: Ready to Merge

#84 Feature/Cart now working great, only left for conecting it with the d…
  src/App.js
  src/Redux/actions.js
  src/components/Cart/cart.jsx
  src/components/Nav/Nav.jsx
Labels: Ready to Merge

#85 features(utils/template_examples/template_01.jsx) create template
  src/utils/img/templates_exemples/template_01.jsx
Labels: Ready to Merge

#86 fix(profile.jsx & action.js) fix localstorage set user
  src/Redux/actions.js
  src/components/Profile/Profile.jsx
Labels: Ready to Merge

#89 Fix/register
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
Labels: Ready to Merge

#90 feature(PresetsDesigns/Basic) create about presets design
  public/index.html
  src/components/PresetsDesigns/Basic/About/BasicAbout01.jsx
Labels: Ready to Merge

#93 Styles
  src/components/Profile/Profile.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
  src/components/shoppingCart/ComponentShop.jsx
  src/components/shoppingCart/Order.jsx
  src/components/shoppingCart/Plantillas.jsx
  src/views/profile/profileView.js
Labels: Ready to Merge

#99 login and registration working
  src/App.js
  src/components/loginComponents/loginComponents.jsx
Labels: Ready to Merge

#102 Feature/Pay
  src/components/Pay/payComponent.jsx
Labels: Ready to Merge

#96 Dev
  .gitignore
  package-lock.json
  package.json
  postcss.config.js
  public/index.html
  src/App.js
  src/Redux/actions.js
  src/Redux/reducer.js
  src/Redux/types.js
  src/components/Banner/Banner.jsx
  src/components/Banner/banner.module.css
  src/components/Cart/cart.jsx
  src/components/Detail/Detail.jsx
  src/components/Footer/Footer.jsx
  src/components/ForgotPassword/ForgotPassword.jsx
  src/components/Home/Home.jsx
  src/components/Home/HomeComponent.jsx
  src/components/Home/home.module.css
  src/components/Nav/Nav.jsx
  src/components/Pay/payComponent.jsx
  src/components/PresetsDesigns/Basic/About/BasicAbout01.jsx
  src/components/PresetsDesigns/Basic/Cart/BasicCart1.jsx
  src/components/PresetsDesigns/Basic/Home/BasicHome1.jsx
  src/components/PresetsDesigns/Basic/Home/BasicHome1.txt
  src/components/PresetsDesigns/Basic/Shop/BasicShop1.jsx
  src/components/Profile/Profile.jsx
  src/components/ResetPassword/ResetPassword.jsx
  src/components/loginComponents/decodeToken.js
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/register.module.css
  src/components/registerComponents/registerComponents.jsx
  src/components/shoppingCart/ComponentShop.jsx
  src/components/shoppingCart/Order.jsx
  src/components/shoppingCart/Plantillas.jsx
  src/components/shoppingCart/shoppingCart.jsx
  src/components/shoppingCart/shoppingCart.module.css
  src/components/shoppingCart/typesAndColors.jsx
  src/components/validation.js
  src/index.js
  src/styles/input.css
  src/styles/output.css
  src/utils/img/exampleModel.json
  src/utils/img/loading.png
  src/utils/img/modelJson.json
  src/utils/img/plantilla.png
  src/utils/img/templates_exemples/template_01.jsx
  src/utils/img/ulisesPresets.json
  src/utils/modelJson.json
  src/utils/templates_exemples/template_01.jsx
  src/views/cart/cart.jsx
  src/views/detail/detail.jsx
  src/views/home/HomeViews.jsx
  src/views/login/index.jsx
  src/views/pay/pay.jsx
  src/views/profile/profileView.js
  src/views/register/index.jsx
  src/views/shoppingCart.jsx
  tailwind.config.js
Labels: Ready to Merge

#107 fix(cart.jsx) fix cart styles
  src/components/Cart/cart.jsx
Labels: Ready to Merge

#108 Fixed ShoppingCart component
  src/components/Detail/Detail.jsx
  src/components/shoppingCart/Plantillas.jsx
Labels: Ready to Merge

#113 fix(plantillas.jsx) fix styles
  src/components/shoppingCart/Plantillas.jsx
Labels: Ready to Merge

#115 Fix/register styles
  src/components/registerComponents/register.module.css
  src/components/registerComponents/registerComponents.jsx
Labels: Ready to Merge

#116 Changes on Detail component
  src/components/Detail/Detail.jsx
Labels: Ready to Merge

#124 fix(profile.jsx) fix default logo & change button 'upload image' for …
  src/components/Profile/Profile.jsx
Labels: Ready to Merge

#125 Fix/home style
  src/components/Home/HomeComponent.jsx
Labels: Ready to Merge

#127 add feature shop
  src/App.js
  src/components/Footer/Footer.jsx
  src/components/shoppingCart/Plantillas.jsx
Labels: Ready to Merge

#129 Bdd/cart
  src/Redux/actions.js
  src/Redux/reducer.js
  src/Redux/types.js
  src/components/Cart/cart.jsx
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
Labels: Ready to Merge

#130 feature(payComponents.jsx) feature paycomponents form and fix styles
  src/components/Pay/payComponent.jsx
Labels: Ready to Merge

#131 Dark Mode created
  public/index.html
  src/components/DarkMode/darkmode.jsx
  src/components/Nav/Nav.jsx
  src/styles/output.css
  tailwind.config.js
Labels: Ready to Merge

#132 feature(basic/home) created a new template
  src/components/PresetsDesigns/Basic/Home/BasicHome02.jsx
Labels: Ready to Merge

#133 Add component, route to about and view
  src/App.js
  src/components/AboutPage/aboutPage.jsx
  src/components/AboutPage/people.jsx
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
  src/views/aboutPage/aboutPage.jsx
Labels: Ready to Merge

#135 Premium Detail Preset
  src/components/PresetsDesigns/Premium/Detail/PremiumDetail1.jsx
Labels: Ready to Merge

#134 Dark mode styles modifications
  src/components/Cart/cart.jsx
  src/components/DarkMode/darkmode.jsx
  src/components/Footer/Footer.jsx
  src/components/Home/HomeComponent.jsx
  src/components/Nav/Nav.jsx
  src/components/Pay/payComponent.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/shoppingCart/ComponentShop.jsx
  src/components/shoppingCart/Order.jsx
Labels: Ready to Merge

#138 Fix/forgot password
  src/components/ForgotPassword/ForgotPassword.jsx
  src/components/Nav/Nav.jsx
  src/components/loginComponents/login.module.css
  src/components/loginComponents/loginComponents.jsx
  src/components/validation.js
Labels: Ready to Merge

#140 fix people and text about
  src/components/AboutPage/aboutPage.jsx
  src/components/AboutPage/people.jsx
Labels: Ready to Merge

#137 feature(PresetsDesigns/Home/BasicHome02.jsx) created setColor pannel
  src/Redux/actions.js
  src/Redux/reducer.js
  src/Redux/types.js
  src/components/PresetsDesigns/Basic/Home/BasicHome02.jsx
  src/utils/ColorPanel.jsx
Labels: Ready to Merge

#146 fix(Home.jsx) fix darkMode colors
  src/components/Banner/Banner.jsx
  src/components/Cart/cart.jsx
  src/components/DarkMode/darkmode.jsx
  src/components/Footer/Footer.jsx
  src/components/Home/HomeComponent.jsx
  src/components/Home/home.module.css
  src/components/Nav/Nav.jsx
  src/components/Pay/payComponent.jsx
  src/components/Profile/Profile.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/register.module.css
  src/components/registerComponents/registerComponents.jsx
  src/components/shoppingCart/ComponentShop.jsx
Labels: Ready to Merge

#147 AboutPage
  src/components/AboutPage/aboutPage.jsx
Labels: Ready to Merge

#148 removed react/admin
  package-lock.json
  package.json
  test-admin/.eslintrc.js
  test-admin/.gitignore
  test-admin/README.md
  test-admin/index.html
  test-admin/package-lock.json
  test-admin/package.json
  test-admin/prettier.config.js
  test-admin/public/favicon.ico
  test-admin/public/manifest.json
  test-admin/src/App.tsx
  test-admin/src/authProvider.ts
  test-admin/src/components/preset/presetList.jsx
  test-admin/src/components/user/userList.jsx
  test-admin/src/dataProvider.ts
  test-admin/src/index.tsx
  test-admin/src/users.json
  test-admin/src/vite-env.d.ts
  test-admin/tsconfig.json
  test-admin/vite.config.ts
Labels: Ready to Merge

#149 fix(Plantillas.jsx) fix style
  src/components/shoppingCart/Plantillas.jsx
Labels: Ready to Merge

#150 config(tailwind) config font
  src/styles/input.css
  src/styles/output.css
  tailwind.config.js
Labels: Ready to Merge

#151 fix(cart.jsx & pay.jsx) fix styles, add Presets's image
  src/Redux/actions.js
  src/components/Cart/cart.jsx
  src/components/Pay/payComponent.jsx
Labels: Ready to Merge

#152 fix types, colors and json presetsUlises
  src/components/shoppingCart/ComponentShop.jsx
  src/components/shoppingCart/typesAndColors.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#153 Many changes
  src/Redux/actions.js
  src/components/Cart/cart.jsx
  src/components/Home/HomeComponent.jsx
  src/components/Pay/payComponent.jsx
  src/components/shoppingCart/Plantillas.jsx
Labels: Ready to Merge

#157 fix/Component
  src/components/Home/HomeComponent.jsx
Labels: Ready to Merge

#159 fix(footer.jsx & payComponent.jsx) resolved Tom's tocs
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
  src/components/Pay/payComponent.jsx
Labels: Ready to Merge

#161 add views presets
  src/App.js
  src/components/Detail/Detail.jsx
  src/components/PreviewPresets/previewPresets.jsx
  src/views/previewPresets/previewPresets.jsx
Labels: Ready to Merge

#164 Detail
  src/components/AboutPage/aboutPage.jsx
  src/components/Detail/Detail.jsx
  src/components/shoppingCart/Plantillas.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#162 Cart/login/feature
  src/components/Cart/cart.jsx
  src/components/Detail/Detail.jsx
  src/components/loginComponents/loginComponents.jsx
Labels: Ready to Merge

#165 Fix/forgot
  package-lock.json
  package.json
  src/components/ForgotPassword/ForgotPassword.jsx
  src/components/ResetPassword/ResetPassword.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
Labels: Ready to Merge

#166 Login Route
  package-lock.json
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
Labels: Ready to Merge

#167 created a preset medium shop, pending to improve
  src/components/PresetsDesigns/Medium/Shop/MediumShop.jsx
  src/components/PreviewPresets/previewPresets.jsx
  src/components/loginComponents/loginComponents.jsx
Labels: Ready to Merge

#168 add pictures About and name's Presets
  src/components/AboutPage/people.jsx
  src/components/PreviewPresets/previewPresets.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#169 Fix Toogle Navigate
  package-lock.json
  src/components/Nav/Nav.jsx
Labels: Ready to Merge

#170 Little fixes
  src/Redux/actions.js
  src/components/Cart/cart.jsx
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
Labels: Ready to Merge

#163 New templates
  public/index.html
  src/components/PresetsDesigns/Basic/Home/BasicHome02.jsx
  src/components/PresetsDesigns/Premium/Home/PremiumHome01.jsx
Labels: No merge please!

#172 Fix(RoutePurchase): Route for GET request of purchases changed
  src/components/Purchases/purchases.jsx
Labels: ready to review, Ready to Merge

#175 add pagination in shop and name/json/preview presets new's
  src/Redux/actions.js
  src/Redux/reducer.js
  src/Redux/types.js
  src/components/PreviewPresets/previewPresets.jsx
  src/components/shoppingCart/Pagination.jsx
  src/components/shoppingCart/Plantillas.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#177 Premium Cart Preset
  src/components/PresetsDesigns/Premium/Cart/PremiumCart01.jsx
Labels: Ready to Merge

#178 fix shop
  src/components/PreviewPresets/previewPresets.jsx
  src/components/shoppingCart/ComponentShop.jsx
  src/components/shoppingCart/Pagination.jsx
  src/components/shoppingCart/Plantillas.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#181 Templates
  src/components/PresetsDesigns/Premium/Cart/PremiumCart01.jsx
  src/components/PresetsDesigns/Premium/Detail/PremiumDetail1.jsx
  src/components/PresetsDesigns/Premium/Home/PremiumHome01.jsx
  src/utils/ColorPanel.jsx
Labels: Ready to Merge

#183 Style Changes on DarkMode component
  src/components/Cart/cart.jsx
  src/components/DarkMode/darkmode.jsx
Labels: Ready to Merge

#173 adding functions, still left the pop up
  .gitignore
  src/components/About/About.jsx
  src/components/About/about.module.css
  src/components/Cart/cart.jsx
  src/components/Home/HomeComponent.jsx
  src/components/Nav/Nav.jsx
  src/components/Pay/payComponent.jsx
  src/components/Purchases/purchases.jsx
  src/components/registerComponents/registerComponents.jsx
  src/views/home/HomeViews.jsx
Labels: Ready to Merge

#186 fix about/login/register
  src/components/AboutPage/about.module.css
  src/components/AboutPage/aboutPage.jsx
  src/components/AboutPage/people.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
  src/components/validation.js
Labels: Ready to Merge

#182 fix(Profile.jsx)
  src/App.css
  src/components/Footer/Footer.jsx
  src/components/Home/HomeComponent.jsx
  src/components/Profile/Profile.jsx
Labels: Ready to Merge

#185 review working allright, now its up to rafa to finish with peticion m…
  src/components/Purchases/purchases.jsx
Labels: Ready to Merge

#187 Presets and Json
  src/components/PreviewPresets/previewPresets.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#189 fixed shop dark ligth mode
  src/components/Pay/payComponent.jsx
  src/components/shoppingCart/ComponentShop.jsx
Labels: Ready to Merge

#190 feature/purchases/pay/profile now you cant be there if you are not lo…
  src/components/Pay/payComponent.jsx
  src/components/Profile/Profile.jsx
  src/components/Purchases/purchases.jsx
Labels: Ready to Merge

#191 Fix/logout
  src/components/Nav/Nav.jsx
  src/components/loginComponents/loginComponents.jsx
  src/components/registerComponents/registerComponents.jsx
Labels: Ready to Merge

#192 Presets img
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#196 fix(Home.jsx) add images to carousel(hardcode) and add comments
  src/components/Home/HomeComponent.jsx
  src/utils/ColorPanel.jsx
Labels: Ready to Merge

#197 fix(Nav.jsx) fix position's bugs
  src/components/Nav/Nav.jsx
Labels: Ready to Merge

#198 Fix/templates
  src/components/PresetsDesigns/Medium/Detail/MediumDetail1.jsx
  src/components/PresetsDesigns/Medium/Shop/MediumShop.jsx
Labels: Ready to Merge

#199 Change presets img url
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#200 Change preset url on Home component
  src/components/Home/HomeComponent.jsx
Labels: Ready to Merge

#201 payment
  src/components/AboutPage/aboutPage.jsx
  src/components/Pay/payComponent.jsx
  src/components/Purchases/purchases.jsx
Labels: Ready to Merge

#202 fixed many things
  src/components/Pay/payComponent.jsx
  src/components/Purchases/purchases.jsx
Labels: Ready to Merge

#203 Cart component
  src/components/Cart/cart.jsx
Labels: Ready to Merge

#204 changes in shop component
  src/components/Nav/Nav.jsx
  src/components/Profile/Profile.jsx
  src/components/shoppingCart/ComponentShop.jsx
  src/components/shoppingCart/Pagination.jsx
  src/components/shoppingCart/Plantillas.jsx
  src/utils/img/ulisesPresets.json
Labels: Ready to Merge

#205 fix(Purchases.jsx & Nav.jsx) fix stile
  src/components/Nav/Nav.jsx
  src/components/Purchases/purchases.jsx
Labels: Ready to Merge

#206 Fixed styles
  src/App.css
  src/App.js
  src/components/Cart/cart.jsx
  src/components/shoppingCart/ComponentShop.jsx
Labels: enhancement, Ready to Merge

#207 Changed messages from the footer
  src/components/Footer/Footer.jsx
Labels: enhancement

#208 Fixed color of the burguer menu not changing depending on the theme
  src/components/Nav/Nav.jsx
Labels: enhancement

#209 Fixed themes button changing the height of the navBar
  src/components/DarkMode/darkmode.jsx
Labels: enhancement

#210 Fixed nav icons not being vertically centered
  src/components/Nav/Nav.jsx
Labels: enhancement

#211 Oopsie
  src/components/Nav/Nav.jsx
Labels: enhancement
